spring:
  profiles:
    active: dev

# 开发环境
---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: register-server-${spring.profiles}
 
eureka: 
  instance:
    hostname: localhost           # eureka服务端的实例名称
  client:
    register-with-eureka: false   # false:表示不需要向注册中心注册自己(默认)
    fetch-registry: false         # false:表示自己是注册中心，负责维护服务实例，不需要去检索服务
    service-url:                  # 集群情况
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 生产环境
---
server:
  port: 9001

spring:
  profiles: pro
  application:
    name: register-server-${spring.profiles}

eureka:
  instance:
    hostname: localhost           # eureka服务端的实例名称
  client:
    register-with-eureka: false   # false:表示不需要向注册中心注册自己(默认)
    fetch-registry: false         # false:表示自己是注册中心，负责维护服务实例，不需要去检索服务
    service-url:                  # 集群情况
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

      
 

 