spring:
  profiles:
    active: pro
---
server:
  port: 8081
spring:
  profiles: pro
  application:
    name: order-application-dev
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    # 数据库名称
    url: jdbc:mysql://localhost:3306/cloud1
    username: root
    password: root
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200
  security:
    user:
      password: user
      name: user
  boot:
    admin:
      client:
        password: user
        instance:
          prefer-ip: true
          metadata:
            user:
              password: user
              name: user
        username: user
eureka:
  # 客户端-注册到eureka服务
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: order-application-pro
    # 显示IP地址
    prefer-ip-address: true

info:
  app.name: order-application-dev
  company.name: shao
  build.artifactId: @project.artifactId@
  build.version: @project.version@
