spring:
  profiles:
    active: dev

# 开发环境
---
server:
  port: 8005

spring:
  profiles: dev
  application:
    name: order-server-${spring.profiles}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    # mysql驱动包
    url: jdbc:mysql://localhost:3306/shao       # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 200    # 等待连接获取的最大超时时间

  cache:
    type: redis
  redis:
    password: redis
    database: 0           # Redis默认情况下有16个分片，这里配置具体使用的分片
    host: 172.22.2.127
    timeout: 10000        # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 8       # 连接池中的最大空闲连接 默认 8
        min-idle: 0       # 连接池中的最小空闲连接 默认 0
        max-active: 8     # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1

  security:
    user:
      name: order
      password: order
  boot:
    admin:
      client:
        url: http://localhost:7777
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          prefer-ip: true

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jiang.springcloud.api.model # 所有Entity别名类所在包
  mapper-locations:                                     # mapper映射文件
    - classpath:mybatis/mapper/**/*.xml

# 注册中心
eureka:
  client:                     # 客户端-注册到eureka服务
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: order-server
    prefer-ip-address: true   # 显示IP地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# 控制台输出SQL
logging:
  level:
    com.shao.mall: DEBUG

info:
  app.name: 订单服务
  company.name: shao
  build.artifactId: @project.artifactId@
  build.version: @project.version@


# 生产环境
---
server:
  port: 9005
spring:
  profiles: pro
  application:
    name: order-server-${spring.profiles}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud1       # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 200    # 等待连接获取的最大超时时间
  security:
    user:
      name: order
      password: order
  boot:
    admin:
      client:
        url: http://localhost:9999  # 监控中心地址
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          prefer-ip: true
eureka:
  client:                           # 客户端-注册到eureka服务
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: order-server
    prefer-ip-address: true         # 显示IP地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  app.name: 订单服务
  company.name: shao
  build.artifactId: @project.artifactId@
  build.version: @project.version@

logging:
  level:
    com.shao.mall: DEBUG