server:
  port: 10002

guid:
  workerId: 0     # 0-31
  datacenterId: 0 # 0-31

spring:
  application:
    name: user-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    # mysql驱动包
    url: jdbc:mysql://localhost:3306/mall_db?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 200    # 等待连接获取的最大超时时间

  cache:
    type: redis
  redis:
    password: redis
    database: 0           # Redis默认情况下有16个分片，这里配置具体使用的分片
    host: localhost
    timeout: 10000ms      # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 8       # 连接池中的最大空闲连接 默认 8
        min-idle: 0       # 连接池中的最小空闲连接 默认 0
        max-active: 8     # 连接池最大连接数(使用负值表示没有限制) 默认 8
        max-wait: -1ms    # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      prefix: /
      suffix: .html
    resources:
      static-locations: classpath:/static/

# 注册中心
eureka:
  client:                     # 客户端-注册到eureka服务
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: user-server
    prefer-ip-address: true   # 显示IP地址

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.jiang.mall.user.api.model     # 所有Entity别名类所在包
  mapper-locations:                                       # mapper映射文件
  - classpath:mapper/**/*.xml

# 控制台输出SQL
logging:
  level:
    com.jiang: DEBUG

# 服务信息
info:
  app.name: 系统服务
  company.name: jiang
  build.artifactId: @project.artifactId@
  build.version: @project.version@

