spring:
  profiles:
    active: dev

# 开发环境
---
server:
  port: 7777

spring:
  profiles: dev
  application:
    name: monitor-server-${spring.profiles}
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    instance-id: monitor-server
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  app.name: 监控中心
  company.name: shao
  build.artifactId: @project.artifactId@
  build.version: @project.version@

# 生产环境
---
server:
  port: 9999

spring:
  profiles: pro
  application:
    name: monitor-server-${spring.profiles}
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    instance-id: monitor-server
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  app.name: 监控中心
  company.name: shao
  build.artifactId: @project.artifactId@
  build.version: @project.version@